### PR TITLE
Rest api add production mode setting andrequest api key ability

### PR DESCRIPTION
**Pull request by Clemmensen**
PR relating to
https://github.com/MercantecData/serverside-programmering-Clemmensen/pull/3#pullrequestreview-323652980

(and issue https://github.com/MercantecData/serverside-programmering-Clemmensen/issues/5 )

- Added a boolean that can be set as to whether to output error details to user or just deliver a statusCode.

- Added a small form to request an api key for the user (not pretty, but will rather look at last assignment and finish instead of looking at bootstrap/css)

### CODE REVIEW

**Comment by Clemmensen** [comment]
Features that could be considered if this was a complete system (Better error pages, a request to get the api key by mail and resent if forgotten and a function to track amount of requests to api and or to limit how often / interval between requests - and also a functionality for admins to access and increase or lower validity from and to length of keys ... plus a lot of booking features with datepicker and other stuff like UI / client)

**Comment by MadsBock** [comment]
I get an error when trying to create the key. How about you?

**Comment by Clemmensen** [comment]
Should be ok now  ... hopefully :P 

`INSERT INTO api_keys (keyphrase, company, contact_person, contact_email, valid_from, valid_to) VALUES ('1c8deba16a123cd9178cd0b00e181645', 'dsadsa', 'saddf', 'grtg', '2019-11-28 14:48:55', '2020-11-28 14:48:55')`

**Review by MadsBock — CHANGES_REQUESTED** [review]
- Hvis man skriver mellemrum i eksempelvis kontaktperson feltet, kommer det ind i databasen som "+".
 - @ bliver til %40

**Comment by MadsBock** [comment]
Hvad med @ tegn i ex. email?

**Comment by Clemmensen** [comment]
@ i email bør være løst med unescape i min commit, men dobbelt checker lige igen
Check - ved mig er det også løst med unescape

**Pull request merged**
